export const env = {
  NODE_ENV: process.env.NODE_ENV ?? 'development',
  BACKEND_URL: process.env.BACKEND_URL,
  SESSION_SECRET_KEY: process.env.SESSION_SECRET_KEY!, // REQUIRED
  SESSION_COOKIE_NAME: process.env.SESSION_COOKIE_NAME ?? '__myapp_session',
  SESSION_MAX_AGE_DAYS: Number(process.env.SESSION_MAX_AGE_DAYS ?? 7),
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  CLOUDINARY_UPLOAD_PRESET: process.env.CLOUDINARY_UPLOAD_PRESET,
}
